apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap }}
data:  
  ALLOWED_HOSTS: "{{ .Values.envvars.ALLOWED_HOSTS  }}"
  APPRISE_ENABLED: "{{ .Values.envvars.APPRISE_ENABLED  }}"
  DB: "{{ .Values.envvars.DB  }}"
  DB_CONN_MAX_AGE: "{{ .Values.envvars.DB_CONN_MAX_AGE  }}"
  DB_HOST: "{{ .Values.envvars.DB_HOST  }}"
  DB_NAME: "{{ .Values.envvars.DB_NAME  }}"
  DB_PASSWORD: "{{ .Values.envvars.DB_PASSWORD  }}"
  DB_PORT: "{{ .Values.envvars.DB_PORT  }}"
  DB_SSLMODE: "{{ .Values.envvars.DB_SSLMODE  }}"
  DB_TARGET_SESSION_ATTRS: "{{ .Values.envvars.DB_TARGET_SESSION_ATTRS  }}"
  DB_USER: "{{ .Values.envvars.DB_USER  }}"
  DEBUG: "{{ .Values.envvars.DEBUG  }}"
  DEFAULT_FROM_EMAIL: "{{ .Values.envvars.DEFAULT_FROM_EMAIL  }}"
  DISCORD_CLIENT_ID: "{{ .Values.envvars.DISCORD_CLIENT_ID  }}"
  DISCORD_CLIENT_SECRET: "{{ .Values.envvars.DISCORD_CLIENT_SECRET  }}"
  EMAIL_HOST: "{{ .Values.envvars.EMAIL_HOST  }}"
  EMAIL_HOST_PASSWORD: "{{ .Values.envvars.EMAIL_HOST_PASSWORD  }}"
  EMAIL_HOST_USER: "{{ .Values.envvars.EMAIL_HOST_USER  }}"
  EMAIL_PORT: "{{ .Values.envvars.EMAIL_PORT  }}"
  EMAIL_USE_TLS: "{{ .Values.envvars.EMAIL_USE_TLS  }}"
  EMAIL_USE_VERIFICATION: "{{ .Values.envvars.EMAIL_USE_VERIFICATION  }}"
  INTEGRATIONS_ALLOW_PRIVATE_IPS: "{{ .Values.envvars.INTEGRATIONS_ALLOW_PRIVATE_IPS  }}"
  LINENOTIFY_CLIENT_ID: "{{ .Values.envvars.LINENOTIFY_CLIENT_ID  }}"
  LINENOTIFY_CLIENT_SECRET: "{{ .Values.envvars.LINENOTIFY_CLIENT_SECRET  }}"
  MASTER_BADGE_LABEL: "{{ .Values.envvars.MASTER_BADGE_LABEL  }}"
  MATRIX_ACCESS_TOKEN: "{{ .Values.envvars.MATRIX_ACCESS_TOKEN  }}"
  MATRIX_HOMESERVER: "{{ .Values.envvars.MATRIX_HOMESERVER  }}"
  MATRIX_USER_ID: "{{ .Values.envvars.MATRIX_USER_ID  }}"
  MATTERMOST_ENABLED: "{{ .Values.envvars.MATTERMOST_ENABLED  }}"
  MSTEAMS_ENABLED: "{{ .Values.envvars.MSTEAMS_ENABLED  }}"
  OPSGENIE_ENABLED: "{{ .Values.envvars.OPSGENIE_ENABLED  }}"
  PAGERTREE_ENABLED: "{{ .Values.envvars.PAGERTREE_ENABLED  }}"
  PD_APP_ID: "{{ .Values.envvars.PD_APP_ID  }}"
  PD_ENABLED: "{{ .Values.envvars.PD_ENABLED  }}"
  PING_BODY_LIMIT: "{{ .Values.envvars.PING_BODY_LIMIT  }}"
  PING_EMAIL_DOMAIN: "{{ .Values.envvars.PING_EMAIL_DOMAIN  }}"
  PING_ENDPOINT: "{{ .Values.envvars.PING_ENDPOINT  }}"
  PROMETHEUS_ENABLED: "{{ .Values.envvars.PROMETHEUS_ENABLED  }}"
  PUSHBULLET_CLIENT_ID: "{{ .Values.envvars.PUSHBULLET_CLIENT_ID  }}"
  PUSHBULLET_CLIENT_SECRET: "{{ .Values.envvars.PUSHBULLET_CLIENT_SECRET  }}"
  PUSHOVER_API_TOKEN: "{{ .Values.envvars.PUSHOVER_API_TOKEN  }}"
  PUSHOVER_EMERGENCY_EXPIRATION: "{{ .Values.envvars.PUSHOVER_EMERGENCY_EXPIRATION  }}"
  PUSHOVER_EMERGENCY_RETRY_DELAY: "{{ .Values.envvars.PUSHOVER_EMERGENCY_RETRY_DELAY  }}"
  PUSHOVER_SUBSCRIPTION_URL: "{{ .Values.envvars.PUSHOVER_SUBSCRIPTION_URL  }}"
  REGISTRATION_OPEN: "{{ .Values.envvars.REGISTRATION_OPEN  }}"
  REMOTE_USER_HEADER: "{{ .Values.envvars.REMOTE_USER_HEADER  }}"
  ROCKETCHAT_ENABLED: "{{ .Values.envvars.ROCKETCHAT_ENABLED  }}"
  RP_ID: "{{ .Values.envvars.RP_ID  }}"
  S3_ACCESS_KEY: "{{ .Values.envvars.S3_ACCESS_KEY  }}"
  S3_BUCKET: "{{ .Values.envvars.S3_BUCKET  }}"
  S3_ENDPOINT: "{{ .Values.envvars.S3_ENDPOINT  }}"
  S3_REGION: "{{ .Values.envvars.S3_REGION  }}"
  S3_SECRET_KEY: "{{ .Values.envvars.S3_SECRET_KEY  }}"
  S3_TIMEOUT: "{{ .Values.envvars.S3_TIMEOUT  }}"
  SECRET_KEY: "{{ .Values.envvars.SECRET_KEY  }}"
  SHELL_ENABLED: "{{ .Values.envvars.SHELL_ENABLED  }}"
  SIGNAL_CLI_SOCKET: "{{ .Values.envvars.SIGNAL_CLI_SOCKET  }}"
  SITE_LOGO_URL: "{{ .Values.envvars.SITE_LOGO_URL  }}"
  SITE_NAME: "{{ .Values.envvars.SITE_NAME  }}"
  SITE_ROOT: "{{ .Values.envvars.SITE_ROOT  }}"
  SLACK_CLIENT_ID: "{{ .Values.envvars.SLACK_CLIENT_ID  }}"
  SLACK_CLIENT_SECRET: "{{ .Values.envvars.SLACK_CLIENT_SECRET  }}"
  SLACK_ENABLED: "{{ .Values.envvars.SLACK_ENABLED  }}"
  SPIKE_ENABLED: "{{ .Values.envvars.SPIKE_ENABLED  }}"
  TELEGRAM_BOT_NAME: "{{ .Values.envvars.TELEGRAM_BOT_NAME  }}"
  TELEGRAM_TOKEN: "{{ .Values.envvars.TELEGRAM_TOKEN  }}"
  TRELLO_APP_KEY: "{{ .Values.envvars.TRELLO_APP_KEY  }}"
  TWILIO_ACCOUNT: "{{ .Values.envvars.TWILIO_ACCOUNT  }}"
  TWILIO_AUTH: "{{ .Values.envvars.TWILIO_AUTH  }}"
  TWILIO_FROM: "{{ .Values.envvars.TWILIO_FROM  }}"
  TWILIO_USE_WHATSAPP: "{{ .Values.envvars.TWILIO_USE_WHATSAPP  }}"
  USE_PAYMENTS: "{{ .Values.envvars.USE_PAYMENTS  }}"
  VICTOROPS_ENABLED: "{{ .Values.envvars.VICTOROPS_ENABLED  }}"
  WEBHOOKS_ENABLED: "{{ .Values.envvars.WEBHOOKS_ENABLED  }}"
  ZULIP_ENABLED: "{{ .Values.envvars.ZULIP_ENABLED  }}"
